/**
 * This code was generated by @basketry/react-query@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit source/path.ext
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://github.com/basketry/basketry/wiki
 * About @basketry/react-query: https://github.com/basketry/react-query#readme
 */

import { mutationOptions, queryOptions } from '@tanstack/react-query';
import { getAuthPermutationService } from './context';
import { CompositeError } from './runtime';

export const allAuthSchemesQueryOptions = () => {
  const authPermutationService = getAuthPermutationService();
  return queryOptions({
    queryKey: ['authPermutation', 'all-auth-schemes', {}] as const,
    queryFn: async () => {
      const res = await authPermutationService.allAuthSchemes();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
    select: (data) => data.data,
  });
};

export const comboAuthSchemesMutationOptions = () => {
  const authPermutationService = getAuthPermutationService();
  return mutationOptions({
    mutationFn: async () => {
      const res = await authPermutationService.comboAuthSchemes();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};
