/**
 * This code was generated by @basketry/react-query@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit source/path.ext
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://github.com/basketry/basketry/wiki
 * About @basketry/react-query: https://github.com/basketry/react-query#readme
 */

import { queryOptions } from '@tanstack/react-query';
import type { ExhaustiveFormatsParams, ExhaustiveParamsParams } from '../types';
import { getExhaustiveService } from './context';
import { CompositeError } from './runtime';

export const exhaustiveFormatsQueryOptions = (
  params?: ExhaustiveFormatsParams,
) => {
  const exhaustiveService = getExhaustiveService();
  return queryOptions({
    queryKey: ['exhaustive', 'exhaustiveFormats', params || {}] as const,
    queryFn: async () => {
      const res = await exhaustiveService.exhaustiveFormats(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
    select: (data) => data.data,
  });
};

export const exhaustiveParamsQueryOptions = (
  params: ExhaustiveParamsParams,
) => {
  const exhaustiveService = getExhaustiveService();
  return queryOptions({
    queryKey: ['exhaustive', 'exhaustiveParams', params || {}] as const,
    queryFn: async () => {
      const res = await exhaustiveService.exhaustiveParams(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
    select: (data) => data.data,
  });
};
