/**
 * This code was generated by @basketry/react-query@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit source/path.ext
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://github.com/basketry/basketry/wiki
 * About @basketry/react-query: https://github.com/basketry/react-query#readme
 */

import { mutationOptions, queryOptions } from '@tanstack/react-query';
import type {
  CreateGizmoParams,
  GetGizmosParams,
  UpdateGizmoParams,
  UploadGizmoParams,
} from '../types';
import { getGizmoService } from './context';
import { CompositeError } from './runtime';

/**
 * Has a summary in addition to a description
 * Has a description in addition to a summary
 */
export const createGizmoMutationOptions = () => {
  const gizmoService = getGizmoService();
  return mutationOptions({
    mutationFn: async (params?: CreateGizmoParams) => {
      const res = await gizmoService.createGizmo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};

/**
 * Only has a summary
 * @deprecated
 */
export const getGizmosQueryOptions = (params?: GetGizmosParams) => {
  const gizmoService = getGizmoService();
  return queryOptions({
    queryKey: ['gizmo', 'getGizmos', params || {}] as const,
    queryFn: async () => {
      const res = await gizmoService.getGizmos(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
    select: (data) => data.data,
  });
};

export const updateGizmoMutationOptions = () => {
  const gizmoService = getGizmoService();
  return mutationOptions({
    mutationFn: async (params?: UpdateGizmoParams) => {
      const res = await gizmoService.updateGizmo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};

export const uploadGizmoMutationOptions = () => {
  const gizmoService = getGizmoService();
  return mutationOptions({
    mutationFn: async (params: UploadGizmoParams) => {
      const res = await gizmoService.uploadGizmo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};
