/**
 * This code was generated by @basketry/react-query@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit source/path.ext
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://github.com/basketry/basketry/wiki
 * About @basketry/react-query: https://github.com/basketry/react-query#readme
 */

import {
  mutationOptions,
  queryOptions,
  type UndefinedInitialDataOptions,
  useMutation,
  type UseMutationOptions,
  useQuery,
  useQueryClient,
  useSuspenseQuery,
} from '@tanstack/react-query';
import type {
  CreateWidgetParams,
  DeleteWidgetFooParams,
  GetWidgetFooParams,
  PutWidgetParams,
  Widget,
} from '../types';
import { getWidgetService, useWidgetService } from './context';
import { CompositeError } from './runtime';

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useMutation } from '@tanstack/react-query';
 * import { createWidgetMutationOptions } from './hooks/widget';
 *
 * const mutation = useMutation(createWidgetMutationOptions());
 * ```
 */
export function useCreateWidget(
  options?: Omit<
    UseMutationOptions<void, Error, CreateWidgetParams, unknown>,
    'mutationFn'
  >,
) {
  const queryClient = useQueryClient();
  const widgetService = useWidgetService();
  return useMutation({
    mutationFn: async (params?: CreateWidgetParams) => {
      const res = await widgetService.createWidget(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      queryClient.invalidateQueries({ queryKey: [`/widgets`] });
      return res.data;
    },
    ...options,
  });
}

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useMutation } from '@tanstack/react-query';
 * import { deleteWidgetFooMutationOptions } from './hooks/widget';
 *
 * const mutation = useMutation(deleteWidgetFooMutationOptions());
 * ```
 */
export function useDeleteWidgetFoo(
  options?: Omit<
    UseMutationOptions<void, Error, DeleteWidgetFooParams, unknown>,
    'mutationFn'
  >,
) {
  const queryClient = useQueryClient();
  const widgetService = useWidgetService();
  return useMutation({
    mutationFn: async (params: DeleteWidgetFooParams) => {
      const res = await widgetService.deleteWidgetFoo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      queryClient.invalidateQueries({
        queryKey: [`/widgets/${params.id}/foo`],
      });
      return res.data;
    },
    ...options,
  });
}

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useMutation } from '@tanstack/react-query';
 * import { putWidgetMutationOptions } from './hooks/widget';
 *
 * const mutation = useMutation(putWidgetMutationOptions());
 * ```
 */
export function usePutWidget(
  options?: Omit<
    UseMutationOptions<void, Error, PutWidgetParams, unknown>,
    'mutationFn'
  >,
) {
  const queryClient = useQueryClient();
  const widgetService = useWidgetService();
  return useMutation({
    mutationFn: async () => {
      const res = await widgetService.putWidget();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      queryClient.invalidateQueries({ queryKey: [`/widgets`] });
      return res.data;
    },
    ...options,
  });
}

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useQuery } from '@tanstack/react-query';
 * import { getWidgetFooQueryOptions } from './hooks/widget';
 *
 * const result = useQuery(getWidgetFooQueryOptions(params));
 * ```
 */
export function useWidgetFoo(
  params: GetWidgetFooParams,
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) {
  const defaultOptions = useGetWidgetFooQueryOptions(params);
  return useQuery({ ...defaultOptions, ...options });
}

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useSuspenseQuery } from '@tanstack/react-query';
 * import { getWidgetFooQueryOptions } from './hooks/widget';
 *
 * const result = useSuspenseQuery(getWidgetFooQueryOptions(params));
 * ```
 */
export function useSuspenseWidgetFoo(
  params: GetWidgetFooParams,
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) {
  const defaultOptions = useGetWidgetFooQueryOptions(params);
  return useSuspenseQuery({ ...defaultOptions, ...options });
}

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useQuery } from '@tanstack/react-query';
 * import { getWidgetsQueryOptions } from './hooks/widget';
 *
 * const result = useQuery(getWidgetsQueryOptions(params));
 * ```
 */
export function useWidgets(
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) {
  const defaultOptions = useGetWidgetsQueryOptions();
  return useQuery({ ...defaultOptions, ...options });
}

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useSuspenseQuery } from '@tanstack/react-query';
 * import { getWidgetsQueryOptions } from './hooks/widget';
 *
 * const result = useSuspenseQuery(getWidgetsQueryOptions(params));
 * ```
 */
export function useSuspenseWidgets(
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) {
  const defaultOptions = useGetWidgetsQueryOptions();
  return useSuspenseQuery({ ...defaultOptions, ...options });
}

const useGetWidgetsQueryOptions = () => {
  const widgetService = useWidgetService();
  return queryOptions({
    queryKey: [`/widgets`],
    queryFn: async () => {
      const res = await widgetService.getWidgets();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
  });
};

export const getWidgetsQueryOptions = () => {
  const widgetService = getWidgetService();
  return queryOptions({
    queryKey: [`/widgets`],
    queryFn: async () => {
      const res = await widgetService.getWidgets();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
  });
};
export const createWidgetMutationOptions = () => {
  const widgetService = getWidgetService();
  return mutationOptions({
    mutationFn: async (params: CreateWidgetParams) => {
      const res = await widgetService.createWidget(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};
export const putWidgetMutationOptions = () => {
  const widgetService = getWidgetService();
  return mutationOptions({
    mutationFn: async () => {
      const res = await widgetService.putWidget();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};
const useGetWidgetFooQueryOptions = (params: GetWidgetFooParams) => {
  const widgetService = useWidgetService();
  return queryOptions({
    queryKey: [`/widgets/${params.id}/foo`],
    queryFn: async () => {
      const res = await widgetService.getWidgetFoo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
  });
};

export const getWidgetFooQueryOptions = (params: GetWidgetFooParams) => {
  const widgetService = getWidgetService();
  return queryOptions({
    queryKey: [`/widgets/${params.id}/foo`],
    queryFn: async () => {
      const res = await widgetService.getWidgetFoo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
  });
};
export const deleteWidgetFooMutationOptions = () => {
  const widgetService = getWidgetService();
  return mutationOptions({
    mutationFn: async (params: DeleteWidgetFooParams) => {
      const res = await widgetService.deleteWidgetFoo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};
