/**
 * This code was generated by @basketry/react-query@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit source/path.ext
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://github.com/basketry/basketry/wiki
 * About @basketry/react-query: https://github.com/basketry/react-query#readme
 */

import {
  mutationOptions,
  queryOptions,
  type UndefinedInitialDataOptions,
  useMutation,
  type UseMutationOptions,
  useQuery,
  useQueryClient,
  useSuspenseQuery,
} from '@tanstack/react-query';
import type {
  CreateWidgetParams,
  DeleteWidgetFooParams,
  GetWidgetFooParams,
  PutWidgetParams,
  Widget,
} from '../types';
import { getWidgetService } from './context';
import { CompositeError } from './runtime';

export const createWidgetMutationOptions = () => {
  const widgetService = getWidgetService();
  return mutationOptions({
    mutationFn: async (params?: CreateWidgetParams) => {
      const res = await widgetService.createWidget(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};

/**
 * @deprecated This mutation hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useMutation } from '@tanstack/react-query';
 * import { createWidgetMutationOptions } from './hooks/widgets';
 *
 * // Old pattern (deprecated)
 * const mutation = useCreateWidget();
 *
 * // New pattern
 * const mutation = useMutation(createWidgetMutationOptions());
 * ```
 */
export const useCreateWidget = (
  options?: Omit<
    UseMutationOptions<void, Error, CreateWidgetParams, unknown>,
    'mutationFn'
  >,
) => {
  const queryClient = useQueryClient();
  const mutationOptions = createWidgetMutationOptions();
  return useMutation({
    ...mutationOptions,
    onSuccess: (data, variables, context) => {
      queryClient.invalidateQueries({ queryKey: ['widget'] });
      mutationOptions.onSuccess?.(data, variables, context);
    },
    ...options,
  });
};

export const deleteWidgetFooMutationOptions = () => {
  const widgetService = getWidgetService();
  return mutationOptions({
    mutationFn: async (params: DeleteWidgetFooParams) => {
      const res = await widgetService.deleteWidgetFoo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};

/**
 * @deprecated This mutation hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useMutation } from '@tanstack/react-query';
 * import { deleteWidgetFooMutationOptions } from './hooks/widgets';
 *
 * // Old pattern (deprecated)
 * const mutation = useDeleteWidgetFoo();
 *
 * // New pattern
 * const mutation = useMutation(deleteWidgetFooMutationOptions());
 * ```
 */
export const useDeleteWidgetFoo = (
  options?: Omit<
    UseMutationOptions<void, Error, DeleteWidgetFooParams, unknown>,
    'mutationFn'
  >,
) => {
  const queryClient = useQueryClient();
  const mutationOptions = deleteWidgetFooMutationOptions();
  return useMutation({
    ...mutationOptions,
    onSuccess: (data, variables, context) => {
      queryClient.invalidateQueries({ queryKey: ['widget'] });
      mutationOptions.onSuccess?.(data, variables, context);
    },
    ...options,
  });
};

export const putWidgetMutationOptions = () => {
  const widgetService = getWidgetService();
  return mutationOptions({
    mutationFn: async () => {
      const res = await widgetService.putWidget();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res.data;
    },
  });
};

/**
 * @deprecated This mutation hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useMutation } from '@tanstack/react-query';
 * import { putWidgetMutationOptions } from './hooks/widgets';
 *
 * // Old pattern (deprecated)
 * const mutation = usePutWidget();
 *
 * // New pattern
 * const mutation = useMutation(putWidgetMutationOptions());
 * ```
 */
export const usePutWidget = (
  options?: Omit<
    UseMutationOptions<void, Error, PutWidgetParams, unknown>,
    'mutationFn'
  >,
) => {
  const queryClient = useQueryClient();
  const mutationOptions = putWidgetMutationOptions();
  return useMutation({
    ...mutationOptions,
    onSuccess: (data, variables, context) => {
      queryClient.invalidateQueries({ queryKey: ['widget'] });
      mutationOptions.onSuccess?.(data, variables, context);
    },
    ...options,
  });
};

export const getWidgetFooQueryOptions = (params: GetWidgetFooParams) => {
  const widgetService = getWidgetService();
  return queryOptions({
    queryKey: ['widget', 'getWidgetFoo', params || {}] as const,
    queryFn: async () => {
      const res = await widgetService.getWidgetFoo(params);
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
  });
};

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useQuery } from '@tanstack/react-query';
 * import { getWidgetFooQueryOptions } from './hooks/widgets';
 *
 * // Old pattern (deprecated)
 * const result = useWidgetFoo(params);
 *
 * // New pattern
 * const result = useQuery(getWidgetFooQueryOptions(params));
 * ```
 */
export const useWidgetFoo = (
  params: GetWidgetFooParams,
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) => {
  const defaultOptions = getWidgetFooQueryOptions(params);
  return useQuery({ ...defaultOptions, ...options });
};

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useSuspenseQuery } from '@tanstack/react-query';
 * import { getWidgetFooQueryOptions } from './hooks/widgets';
 *
 * // Old pattern (deprecated)
 * const result = useSuspenseWidgetFoo(params);
 *
 * // New pattern
 * const result = useSuspenseQuery(getWidgetFooQueryOptions(params));
 * ```
 */
export const useSuspenseWidgetFoo = (
  params: GetWidgetFooParams,
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) => {
  const defaultOptions = getWidgetFooQueryOptions(params);
  return useSuspenseQuery({ ...defaultOptions, ...options });
};

export const getWidgetsQueryOptions = () => {
  const widgetService = getWidgetService();
  return queryOptions({
    queryKey: ['widget', 'getWidgets', {}] as const,
    queryFn: async () => {
      const res = await widgetService.getWidgets();
      if (res.errors.length) {
        throw new CompositeError(res.errors);
      } else if (!res.data) {
        throw new Error('Unexpected data error: Failed to get example');
      }
      return res;
    },
  });
};

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useQuery } from '@tanstack/react-query';
 * import { getWidgetsQueryOptions } from './hooks/widgets';
 *
 * // Old pattern (deprecated)
 * const result = useWidgets(params);
 *
 * // New pattern
 * const result = useQuery(getWidgetsQueryOptions(params));
 * ```
 */
export const useWidgets = (
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) => {
  const defaultOptions = getWidgetsQueryOptions();
  return useQuery({ ...defaultOptions, ...options });
};

/**
 * @deprecated This hook is deprecated and will be removed in a future version.
 * Please use the new query options pattern instead:
 *
 * ```typescript
 * import { useSuspenseQuery } from '@tanstack/react-query';
 * import { getWidgetsQueryOptions } from './hooks/widgets';
 *
 * // Old pattern (deprecated)
 * const result = useSuspenseWidgets(params);
 *
 * // New pattern
 * const result = useSuspenseQuery(getWidgetsQueryOptions(params));
 * ```
 */
export const useSuspenseWidgets = (
  options?: Omit<
    UndefinedInitialDataOptions<Widget, Error, Widget | undefined, string[]>,
    'queryKey' | 'queryFn' | 'select'
  >,
) => {
  const defaultOptions = getWidgetsQueryOptions();
  return useSuspenseQuery({ ...defaultOptions, ...options });
};
